version: '3'
services:

 mysql:
#  image: mariadb
  build: mariaDB
    #  command:
          #   - sh start.sh
#  environment:
#   MYSQL_ROOT_PASSWORD: 112233kyky
#   MYSQL_DATABASE: db_wordpress
#   MYSQL_USER: bwayfare
#   MYSQL_PASSWORD: 112233kyky
  volumes:
   - db_vol:/var/lib/mysql/
  restart: always

 wordpress:
#  image: wordpress
  build: wordpress
    #  command:
          #   - mv /wordpress/* /var/www/my_site/
          #   - cp /wp-config.php /var/www/my_site/
          #   - sh start.sh
  depends_on:
   - mysql
#  environment:
#   WORDPRESS_DB_HOST: mysql
#   MYSQL_ROOT_PASSWORD: 112233kyky
#   WORDPRESS_DB_NAME: db_wordpress
#   WORDPRESS_DB_USER: bwayfare
#   WORDPRESS_DB_PASSWORD: 112233kyky
#   WORDPRESS_TABLE_PREFIX: wp_
  links:
   - mysql
  volumes:
   - wp_vol:/var/www/
  restart: always

 nginx:
#  image: nginx
  build: nginx
  depends_on:
   - wordpress
  ports:
   - 443:443
  links:
   - wordpress
  volumes:
   - wp_vol:/var/www/my_site

volumes:
 db_vol:
  driver: local
  driver_opts:
   type: "none"
   o: bind
   device: "/home/ecole42-school21/inception/data/database"
 wp_vol:
  driver: local
  driver_opts:
   type: "none"
   o: bind
   device: "/home/ecole42-school21/inception/data/wordpress"
