version: '3.3'

services:
 mysql_svc:
  build: mariaDB
  container_name: mysql
  environment:
   - DB_NAME=wordpress
   - DB_PASSWORD=wordpress
   - DB_USER=wordpress
  networks:
   - inception_net
  volumes:
   - db_vol:/var/lib/mysql/
  restart: always
 nginx_svc:
  build: nginx
  container_name: nginx
  networks:
   - inception_net
  depends_on:
   - wordpress_svc
  ports:
   - 443:443
  volumes:
   - wp_vol:/var/www/
  extra_hosts:
   - "bwayfare.42.fr:127.0.0.1"
 wordpress_svc:
  build: wordpress
  container_name: wordpress
  environment:
   - DB_HOST=mysql_svc:3306
   - DB_USER=wordpress
   - DB_PASSWORD=wordpress
   - DB_NAME=wordpress
  networks:
   - inception_net
  depends_on:
   - mysql_svc
  volumes:
   - wp_vol:/var/www/
  command: "sh ./start.sh"
  restart: always

networks:
 inception_net:

volumes:
 db_vol:
  driver: local
  driver_opts:
   type: "none"
   o: "bind"
   device: ${PWD}/data/database
 wp_vol:
  driver: local
  driver_opts:
   type: "none"
   o: "bind"
   device: ${PWD}/data/wordpress
