version: '3.3'

services:
 mysql_svc:
  build: mariaDB
  container_name: mysql
  networks:
   - inception_net
  volumes:
   - db_vol:/var/lib/mysql/
  restart: always
 wordpress_svc:
  build: wordpress
  container_name: wordpress
  networks:
   - inception_net
  depends_on:
   - mysql_svc
  volumes:
   - wp_vol:/var/www/
  restart: always
 nginx_svc:
  build: nginx
  container_name: nginx
  networks:
   - inception_net
  depends_on:
   - wordpress_svc
  ports:
   - 443:443
  volumes:
   - wp_vol:/var/www/

networks:
 inception_net:

volumes:
 db_vol:
  driver: local
  driver_opts:
   type: "none"
   o: "bind"
   device: "/home/ecole42-school21/inception/srcs/data/database"
 wp_vol:
  driver: local
  driver_opts:
   type: "none"
   o: "bind"
   device: "/home/ecole42-school21/inception/srcs/data/wordpress"
