version: '3.3'

services:
 mariadb_svc:
  build: ./requirements/mariadb
  container_name: mariadb
  env_file: .env
  networks:
   - docker-network
  volumes:
   - db_vol:/var/lib/mysql/
  restart: always
 nginx_svc:
  build: ./requirements/nginx
  container_name: nginx
  env_file: .env
  networks:
   - docker-network
  depends_on:
   - wordpress_svc
  ports:
   - 443:443
  volumes:
   - wp_vol:/var/www/
  extra_hosts:
   - ${DOMAIN_NAME}:127.0.0.1
 wordpress_svc:
  build: ./requirements/wordpress
  container_name: wordpress
  env_file: .env
  networks:
   - docker-network
  depends_on:
   - mariadb_svc
  volumes:
   - wp_vol:/var/www/
  restart: always

networks:
 docker-network:

volumes:
 db_vol:
  driver: local
  driver_opts:
   type: "none"
   o: "bind"
   device: /home/${USER}/data/database
 wp_vol:
  driver: local
  driver_opts:
   type: "none"
   o: "bind"
   device: /home/${USER}/data/wordpress
