version: '3'
services:

 mysql:
#  image: mariadb
  build: mariaDB
  volumes:
   - ./data/database:/var/lib/mysql
     #  command:
          #   - sh start.sh
#  environment:
#   MYSQL_ROOT_PASSWORD: 112233kyky
#   MYSQL_DATABASE: db_wordpress
#   MYSQL_USER: bwayfare
#   MYSQL_PASSWORD: 112233kyky
  restart: always

 wordpress:
#  image: wordpress
  build: wordpress
  volumes:
   - ./data/wordpress:/var/www/my_site
     #  command:
          #   - mv /wordpress/* /var/www/my_site/
          #   - cp /wp-config.php /var/www/my_site/
          #   - sh start.sh
  depends_on:
   - mysql
#  environment:
#   WORDPRESS_DB_HOST: mysql
#   MYSQL_ROOT_PASSWORD: 112233kyky
#   WORDPRESS_DB_NAME: db_wordpress
#   WORDPRESS_DB_USER: bwayfare
#   WORDPRESS_DB_PASSWORD: 112233kyky
#   WORDPRESS_TABLE_PREFIX: wp_
  links:
   - mysql
  restart: always

 nginx:
#  image: nginx
  build: nginx
  volumes:
   - ./wordpress/data:/var/www/my_site
  ports:
   - 443:443
  links:
   - wordpress

volumes:
  data:
