CREATE DATABASE IF NOT EXISTS SQL_CONF_NAME;
GRANT ALL ON *.* TO 'SQL_CONF_USER' IDENTIFIED BY 'SQL_CONF_PASS' WITH GRANT OPTION;
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'SQL_CONF_ROOT_PASS';